### ISSUE TITLE
Allow turning off Particles to save GPU Usage

### ISSUE THREAD

**Issue by aydendevnova** [Mad-Cookies-Studio/mad-productivity#18]
Low Processor Mode is On, however the particles force the screen to constantly update. On laptops this is an issue because GPU usage is always up high. When the particles are hidden the GPU usage drops. 
I want to use this app however battery life on my laptop matters when I am away from a plug, and I want the usage to be as low as possible.
Other optimizations could be made by caching node paths (dont use $NodeName), cache it into a variable onready and use that instead. (I have heard get_node is an expensive call, it may help to reduce those. as well, but I don't think it is a big deal.)

**Comment by lentsius-bark** [comment]
This is a fabulous idea which I'm super surprised we hadn't thought of till now. One of us will get to it when we have time, but also feel free to implement it if you feel like it.
It'll need a setting, _ready set up and lastly listen in for the signal of the settings changed.

Thanks for posting the issue.

**Comment by lentsius-bark** [comment]
The particle setting is implemented by 7237cd8996849ca97d6406cb7ff10938e9c61050

I created a seperate issue for the caching of nodes (#21) so that that part is not forgotten about
