### ISSUE TITLE
`.import` directory included in repo.

### ISSUE THREAD

**Issue by Sslaxx** [Mad-Cookies-Studio/mad-productivity#8]
The `.import` directory is usually not included with repos.

https://raw.githubusercontent.com/Sslaxx/Godot_Sonic_Engine/master/.gitignore might be helpful to look at to exclude certain types of file that don't need to be in the repository.

**Comment by lentsius-bark** [comment]
@Sslaxx Aha! Good stuff over there, I'll go ahead do work it into this repo as well.

**Comment by lentsius-bark** [comment]
fixed by 603315215088378e761623ed4748e6bebff14e81
